### ISSUE TITLE
Request an upgrade mod

### ISSUE THREAD

**Issue by Koalemon** [chsbuffer/NoteBetter#1]
I noticed your mod. But they don't have version 1.19 and above, and I'm looking forward to whether this mod is going to be updated or not.

**Comment by chsbuffer** [comment]
I will look into it. Remind me if no update for a month

**Comment by Koalemon** [comment]
Very willing, looking forward to the update!

**Comment by chsbuffer** [comment]
There are two new releases, one for 1.16.5~1.19.2, and the other for >=1.19.3.

**Comment by Koalemon** [comment]
> There are two new releases, one for 1.16.5~1.19.2, and the other for >=1.19.3.

Very, very fast efficiency, thank you for your release!
